build:
    environment:
        php: '5.5.0'
    dependencies:
        before:
            - mysql -uroot -e "create database IF NOT EXISTS mysqltcs;"
            - mysql -uroot -e "CREATE USER 'mysqltcs'@'localhost' IDENTIFIED BY 'zhhnqBF26wtnUnP9';"
            - mysql -uroot -e "GRANT ALL ON mysqltcs.* TO 'mysqltcs'@'localhost';"
            - mysql -uroot -e "CREATE TABLE IF NOT EXISTS `test1` (`id` int(11) NOT NULL, `value` varchar(50) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=latin1; ALTER TABLE `test1` ADD PRIMARY KEY (`id`); ALTER TABLE `test1` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;"
    tests:
        override:
            -
                command: 'phpunit'
                coverage:
                    file: 'coverage.xml'
                    format: 'php-clover'

