build:
    environment:
        php: '5.5.0'

before_commands:
    - composer self-update
    - composer install --prefer-source --no-interaction
    - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS mysqltcs;" -uroot; fi
    - if [[ "$DB" == "mysql" ]]; then mysql -e "CREATE USER 'mysqltcs'@'localhost' IDENTIFIED BY 'zhhnqBF26wtnUnP9';" -uroot; fi
    - if [[ "$DB" == "mysql" ]]; then mysql -e "GRANT ALL ON mysqltcs.* TO 'mysqltcs'@'localhost';" -uroot; fi


build:
    tests:
        override:
                command: 'phpunit'
                coverage:
                    file: 'coverage.xml'
                    format: 'php-clover'

