build:
    environment:
        php: '5.5.0'

build:
    tests:
        override:
                command: 'phpunit'
                coverage:
                    file: 'coverage.xml'
                    format: 'php-clover'

