build:
    environment:
        php: '5.5.0'
    dependencies:
        before:
            - mysql -uroot -e "create database IF NOT EXISTS mysqltcs;"
            - mysql -uroot -e "CREATE USER 'mysqltcs'@'localhost' IDENTIFIED BY 'zhhnqBF26wtnUnP9';"
            - mysql -uroot -e "GRANT ALL ON mysqltcs.* TO 'mysqltcs'@'localhost';"
            - mysql -uroot -e mysqltcs < tests/mysqltcs.sql
    tests:
        override:
            -
                command: 'phpunit'
                coverage:
                    file: 'coverage.xml'
                    format: 'php-clover'

