# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm


# optionally specify a list of environments, for example to test different RDBMS
env:
  - DB=mysql

# Commands to be run before your environment runs.
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS mysqltcs;" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "CREATE USER 'mysqltcs'@'localhost' IDENTIFIED BY 'zhhnqBF26wtnUnP9';" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "GRANT ALL ON mysqltcs.* TO 'mysqltcs'@'localhost';" -uroot; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "CREATE TABLE IF NOT EXISTS `test1` (`id` int(11) NOT NULL, `value` varchar(50) NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=latin1; ALTER TABLE `test1` ADD PRIMARY KEY (`id`); ALTER TABLE `test1` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;" -uroot; fi

# Commands you want to run that will verify your build.
script: phpunit

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm


# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: always